version: '3.9'

services:
  postgres:
    container_name: cs-repro-postgres
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
      - LISTEN_ADDRESS="*"
    image: postgres:13-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U mmuser -d mattermost
      interval: 10s
      timeout: 3s
      retries: 3
  openldap:
    container_name: cs-repro-openldap
    hostname: openldap
    restart: unless-stopped
    image: rroemhild/test-openldap:latest
    ports:
      - "10389:10389"
      - "10636:10636"
  prometheus:
    container_name: cs-repro-prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./files/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./volumes/prometheus:/prometheus
  grafana:
    container_name: cs-repro-grafana
    image: grafana/grafana:7.5.7
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./files/grafana/dashboards:/var/lib/grafana/dashboards
      - ./files/grafana/provisioning:/etc/grafana/provisioning
      - ./volumes/grafana:/var/lib/grafana
  mattermost:
    platform: linux/amd64
    container_name: cs-repro-mattermost
    depends_on:
      postgres:
        condition: service_healthy
    image: mattermost/mattermost-enterprise-edition:release-7.5
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    read_only: false
    ports:
      - "8065:8065"
      - "8067:8067"
    tmpfs:
      - /tmp
    volumes:
      - ./volumes/mattermost/config:/mattermost/config:rw
      - ./volumes/mattermost/data:/mattermost/data:rw
      - ./volumes/mattermost/logs:/mattermost/logs:rw
      - ./volumes/mattermost/plugins:/mattermost/plugins:rw
      - ./volumes/mattermost/client/plugins:/mattermost/client/plugins:rw
      - ./volumes/mattermost/bleve-indexes:/mattermost/bleve-indexes:rw
      - ./enterprise.txt:/mattermost/config/license.mattermost-enterprise:ro
      - ./files/mattermost/config.json:/mattermost/config/config.json
      - ./files/mattermost/samlCert.crt:/mattermost/config/samlCert.crt
      # - ./certs/mattermost.crt:/mattermost/config/mattermost.crt:rW
  keycloak:
    container_name: cs-repro-keycloak
    platform: linux/amd64
    image: keycloak/keycloak:18.0.0
    volumes:
      - ./volumes/keycloak:/opt/keycloak/data:rw
    environment:
      - PROXY_ADDRESS_FORWARDING="true"
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
    command:
      - start-dev