
version: '3'

volumes:
  postgres_data:
      driver: local

services:
  # postgres:
  #     image: postgres
  #     volumes:
  #       - postgres_data:/var/lib/postgresql/data
  #     environment:
  #       POSTGRES_DB: keycloak
  #       POSTGRES_USER: keycloak
  #       POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      # KC_DB_VENDOR: POSTGRES
      # DB_ADDR: postgres
      # DB_DATABASE: keycloak
      # : keycloak
      # DB_SCHEMA: public
      # DB_PASSWORD: password
      # KC_DB_URL: 'jdbc:postgresql://postgres/keycloak'
      # KC_DB_USERNAME: keycloak
      # KC_DB: postgres
      # KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
      # KC_HOSTNAME: keycloak
      # KC_HOSTNAME_PORT
    # volumes:
    #   - ./volumes/keycloak:/opt/jboss/keycloak/standalone/data/
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy